### ISSUE TITLE
Format isn't applied if an image is saved without an extension

### ISSUE THREAD

**Issue by kieraneglin** [elixir-mogrify/mogrify#77]
## Expected
I can format and save an image without an extension, like so:

```elixir
import Mogrify

open("image.jpg")
|> format("png")
|> save(path: "no_extension") 

open("no_extension")
|> verbose # Has type of png, even though there's no extension
```

## Actual
When performing the above actions, the newly saved file maintains its original type

## Workaround
```elixir
import Mogrify

image = open("image.jpg")
  |> format("png")
  |> save()

File.rename(image.path, "no_extension")

open("no_extension")
|> verbose # Has type of png, as expected
```

**Comment by talklittle** [comment]
Thanks for the report. Reproducible with test:

```elixir
  test ".format when output path has no extension" do
    orig = open(@fixture) |> verbose
    assert "jpeg" == orig.format

    path = Path.join(System.tmp_dir(), "mogrify_test_no_ext")

    orig
    |> format("png")
    |> save(path: path)

    image =
      open(path)
      |> verbose

    assert "png" == image.format
  end
```

**Comment by talklittle** [comment]
Seems like `convert` is more suitable in general. https://www.imagemagick.org/Usage/basics/#mogrify_convert

Probably not a viable solution here, though, since it will change too much of how this library works. We might need to use your workaround involving a temp file and renaming the result to the desired filename.

**Comment by talklittle** [comment]
Mogrify v0.9.0 (this library) uses `convert` instead of `mogrify` now (except when `in_place: true` is passed to `save/2`).

It still breaks in this case because the `convert` command will ignore the `-format` flag. The output file needs to explicitly contain the file extension. So we probably want to detect when the requested format does not match the requested path's file extension. In that case we should use the temp file workaround, and rename the result to the desired filename.
